### ISSUE TITLE
How to use both react-cookie and use cookies outside of react components?

### ISSUE THREAD

**Issue by davidfurlong** [reactivestack/cookies#93] opened 2017-07-19 19:12 UTC
I'm upgrading and its not clear to me how I can both use this library with react SSR and use it outside of components. I've tried initialising '(new Cookies()).get(...)' etc but I get the error that I'm missing the cookie header or object (seems because I didn't supply an argument to the Cookies constructor). Do I even need to use this library in those cases? Do I need to avoid those cases? Seems like I can do all that using `universal-cookies`, so does that play nice with `react-cookies` (I can see that `react-cookies` depends on it for `Cookies`

I'd appreciate a suggestion of how to proceed. 

Edit: Essentially all `react-cookies` does is add HOCs to add `universal-cookies Cookies` to the  react `context`, right?

**Comment by adambarghouthi** [comment] 2017-07-30 01:53
Hey @davidfurlong - did you figure this out? I'm thinking about the same thing because I want to send state from localStorage back to the server for SSR in a cookie

**Comment by davidfurlong** [comment] 2017-07-31 07:31
@adambarghouthi Yes I did but it wasn't pretty.   

```js
// cookies.js

import { Cookies as ReactCookies } from 'react-cookie';

const warning = () => {
  return false;
};

class Cookies {
  constructor() {
    if (typeof window !== 'undefined') this._cookies = new ReactCookies();
    else
      this._cookies = {
        get: warning,
        set: warning,
        remove: warning,
      };
  }
  setCookies(opts) {
    this._cookies = new ReactCookies(Object.assign({}, opts));
  }
  get cookies() {
    return this._cookies;
  }
}

export const cookies = new Cookies();
export const getUniversalCookies = () => cookies.cookies;

```js
// authentication.js (an example use of it)
import { getUniversalCookies } from '../cookies';
import { authenticationInterface } from 'reducks/interfaces';

authenticationInterface.implements({
  store: (key, val, opts) => getUniversalCookies().set(key, val, opts),
  load: key => getUniversalCookies().get(key),
  destroy: (key, opts = { path: '/' }) =>
    getUniversalCookies().remove(key, opts),
  platform: 'web',
});

export default authenticationInterface;

```

```js
// serverRender.js
import { getUniversalCookies, cookies } from './cookies';
import { CookiesProvider } from 'react-cookie';
...
function(request, response){
...
const universalCookies = request.universalCookies.getAll();
cookies.setCookies(universalCookies);

render(<CookiesProvider cookies={getUniversalCookies()}>...</CookiesProvider>);
```

client as in example

**Comment by adambarghouthi** [comment] 2017-07-31 13:13
Thanks @davidfurlong, I decided to just just use the `universal-cookies` library - all I need is to persist the state of a shopping cart on server and client

**Comment by iszak** [comment] 2017-08-09 13:31
@davidfurlong You shouldn't need a wrapper, you should be able to pass in the universal cookies instance to the `<CookiesProvider />` assuming it's an instance of https://github.com/reactivestack/cookies/blob/master/packages/universal-cookie/src/Cookies.js since `react-cookie` uses `universal-cookie` see https://github.com/reactivestack/cookies/blob/master/packages/react-cookie/src/CookiesProvider.js#L12 for what the prop expects.

You should also be careful with your solution because your cookie wrapper as exported as a module is a singleton which will be shared across all requests in node.js in a given thread.

**Comment by wayweary** [comment] 2017-08-16 08:15
This has to be a very common use case, i would love an example on how to achieve this. I mean, if all components use the same wrapping method to set cookies it will be much easier to add/remove behaviour before or after setting a cookie.   

Just posted a relating Stackoverflow question https://stackoverflow.com/questions/45708003/using-react-cookie-in-a-util-file

**Comment by eXon** [comment] 2017-09-03 18:50
I think the discussion belong more to SO than within a bug issue so I'm closing this

**Closed by eXon** 2017-09-03 18:50 UTC

**Comment by sebmor** [comment] 2017-10-11 15:31
Even though its not a bug, I too struggled with this, ideally react-cookie provides this along their documentation as this is such a common use case

**Comment by Jake-Mulhern** [comment] 2023-02-22 18:38
Has there been a solution to this?  I set my access and refresh tokens as cookies and would like to automatically access these when creating an axios instance.  However, I cannot because it is in a utility function and not inside of a component.
